### ISSUE TITLE
Is it possible to open webpage without downloading the HTML file?

### ISSUE THREAD

**Issue by ashlinrichardson** [ecsendmail/AgentBasedModel#2]
Hi Ernie,
Is it possible to open webpage without downloading the HTML file?

Here's one example of github functioning as a web server:

https://www.finex.co/how-to-display-html-in-github/

cheers,
Ash

**Comment by ashlinrichardson** [comment]
If you could have your simulation open without needing to download or install anything Ernie, that would give your model a strong advantage over your competitors!

**Comment by ecsendmail** [comment]
That helps...glad someone has done the work (AND YOU FOUND IT TOO, thank
you thank you)...
Later today
Ernie

**Comment by ashlinrichardson** [comment]
Thanks Ernie for setting this up!
